# vercel pipeline portfolio

name: Portfolio Vercel 
on: [push]
jobs: 
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text}}
    env: 
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0' 
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Sets the vercel env
        run: |
          cd .next
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}" > project.json
      - name: Deploying the project
        # env:
        #   VERCEL_TOKEN: z3rpISD7iiYfoSpt8K7HPmRj
        #   VERCEL_ORG_ID: xw9uT9ETKLF6Lg0wx74k6A6Z
        #   VERCEL_PROJECT_ID: prj_oEkeADMfrKUGKCeXgU7HUgdONcvB
        run: yarn deploy
      - name: Setup finish
        id: finished
        run: echo "::set-output-name=text::hello-world"
      # - run: true
      # - run: echo "hello world!!!"
      # - run: echo "this is step 2"
  test-app:
    needs: build-ap
    runs-on: ubuntu-latest
    env:
      MY_JOB_OUTPUT: ${{ needs.build-app.outputs.text}}
    steps:
      - run: echo $MY_JOB_OUTPUT